#pragma once

#include <Arduino.h>

// Generated by tools/gen_faces.py from docs/faces.json: do not edit.
// The clock faces that can be installed, in the order of faces.json.
struct FaceInfo {
  const char *id, *name;
  char key;        // telnet key that installs it
  bool fits32;     // drawn for a 64x32 panel too
  const char *iconPalette;  // 16 colours as rrggbb, or nullptr when there is no picture
  const char *iconPixels;   // 32x32, base64 of 4 bits per pixel, first pixel in the high half
};

static const FaceInfo CW_FACES[] = {
  {"0x0B", "Football", 'B', false,
    "cdebd68eba9dac947b8b938f70685a3885533586523d52493834392e292b27272b27272a27272926272927262a262629",
    "VWVmZVVlVmVWZVZVVmVVVWAwMDVgMRFmZmVjAxYzARVhURFmYBYWZVZlYRUWMwMFUTMzZWE1NWVWVVMTFlMWNXd3d3d3d3d3d3d3"
    "d3d3d3fvu8z7v8vM3d3MvPu/zLv+5EiES7u7u7u7u7u7sziDO4IiIii7ABu7u7AL+4AAAAiEIiJIv3cLu7u4C/uDAAA4viIi67u0"
    "D6AKuwu7uwAAu/0iIuu/QIu7u7sL+7sAAL+9IiLruwA7+7+zA7u8AAC7vtruq7szO7u7szO7u7u7u7v7u7v/u7+7u/u7+7u7v7s7"
    "MDQDS7u7u7u7u7MzOzQwBDA7Ozv7u7/7u7+zNDMzuzQzvTs7+7u/+7u/s7s7A7BLQzQz+7u7u7u7u7QzS08zu/u7//+7v7u7+7v/"
    "/7u/u7u7o7u7u7u7u7uju7u7u7u/+zA7u/u/+7/7MDu7+7/73M3DzO2qzczO3KPbu7u73+EREREREREREREREImYiIu727vbvbs7"
    "u7t8u9u/u7u7u7u7+7/zA7u8S7v7v7u7u7zMyrzMzDzMzKzMzMzMzMvYiIiIiIiIiIiIiIiIiIiP27v7u7v+67u7u7u7u7u76kMz"
    "QzMzvh67p0S7BDAKNOdDNENDM746czR0uzuzw7PnQ8tKM7u7Oru0dOs787Mw54Qzs0S7/Te//UjrNLS0tOg="},
  {"0x0C", "Formula 1", 'F', false,
    "d7b7b5989293ac91938c8d8e717172457d75be3d3a605f62484c504a434895262727272b27272a27272927262a262629",
    "YGZmYGZmZmZmZmZmZmYGBmBgAGBmZmZmZmZmZmBmBgZgAABgZmZmZmZmZmZgBgAGZmZmZmZmZmZmZmZmZmZmZr3v/d7N7t/d3f7u"
    "2+69u76U9VcRFwzM/u/MzPPDODM7tPVRARwczMzMzMzD04MjO5T4h3d8fMzMzMzM+Dg4iI+D1VERFxzMzMzMzIzENDQ8RLVRERwc"
    "zMzMzNg8xEQ0PYTIh3cXfMz8z8zM/IhISE2D6qEXEQzP/M/8zo7YNDhMk9qhAQEMzMzMzMg8tERNTITpl3d3fM/MzPzMz4hISExE"
    "6qHhFxzMzMzM3Y/4OEg/g9qhwXHMzM/8zMg+6DxOTNjZlxccHMzP/MzP7YhITYxE53ERARzMzMzMzI/0RERNg+dxEREcz8zM/Ng8"
    "+Dg4PIS5l3cXfMzMzMzMzIyISExE53EXBxzP/M/8zo3USDQ8Q9dxexEMzPzPzMg8xDRET4T5l8cXfMzMzMzMzYhISEyD5VERERzM"
    "zMzMvIzINEg8tPVREXEczMzMzMg9z0g0TdjYjHcXfMzMzMzMzIyMiE1D5VcRwQzM/M/MzIzEOEhPQ/VRAcEcz/zP/Ng8yDxNTITJ"
    "l3cXHMzMzMzM7ohISE5D1EcXFx/PzMz7iE/0ODQ8g9RBEQsczMzMyD5P9Eg0TYTojBd3fMzP/M3ITohISEw="},
  {"0x08", "Tetris", '8', true,
    "fcfc5980f7c349f2e392a162666fc8368c7071366e25282a37272927272b27272a27272826272bd724263f262a27262a",
    "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8vKmvqqq3qqq8ynr5n7y7tEQiK6qq3aqqREIisiywC7QAAC+qq92qqkAA"
    "ApIs8AqqqX3aqqoiqqqqlyCyL/ALr/r92qqnIKqq+Xkgoi+gCvREIi+qqiCqqURCILREIiyUAAArqqkAqqpAAAC0AAApcEypqqqr"
    "AKqqqard+pqt2nBHf7+qqgKqqr+r3Zqqzd9wRE3cqqsCqqogAASaqr3awERN2qqrIpqpIiREyqqd15n/nK+qq7eqqnrMuZqq/8eq"
    "qaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvr7/7v7r6qqv/y5"
    "/7+vqqqpUlkwOqqqqu3mNRIlqqqqqlJfMDyqqqrt5kNTRaqqqqpSXzA3qqqqUlY19kaqqqqqUlswN6Y2qlE1VfY1qqqqqmREIlyW"
    "NqpRNTb1VZqqqqpjAAFamqqqMDZGpVWqqqqqzP/t7KqqqjAzNvVVqqqqqqqr7eqqqqoxUza1Jaqqqqqqq+3rqqqqMVM0MzWqqqqq"
    "qq/t76qqqlJTMzMlqqqq+qqvv3+vqqr6uc/Mmq+qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqo="},
  {"0x01", "Mario", '1', false,
    "edc9859fc78fcb9d6b62a34da57a5b6a7146a15046414040311a4d100e690c0b720d09740b0b72090b73090c6f0a0a74",
    "zP7t2uzOz87t2VnOrd6vzMv6z/rLrKu8z/QFzK/8y7zLqs3Kz/y9/My1Bbys/Mu866yu+suurN7tqVnMreqonpis74IiIiIlYiIi"
    "IinegBUQGZ11UgIihSgiACVY2BAAEAEZciIiIiUiICICCFAAAAAAAXR3cHglIlgieCgQABAAAAVyJ3BYJSJXB0goxREBEQEZdIIC"
    "WAUlKFVYKP+ZiZmMr3RVUFVFJFUiJSj9ys3vqu50QgICVSUgIiRI7uzOyWR8dEIiIlUlIiIkSM6sqpYmabiIiIiImIiIiIn/q7yC"
    "ZB362/693d3by7/P3e28hmG92uzOrc7tzO3Or97szoZkHtrszq3O7cztzq/e7M6WImn62/693d3by7/P3e28yWZ7u6u8q7vNuq/U"
    "S/+r/ciBiMrrrqqsysZmYgrOrYeVMTWe7N7qru6XJAEa7uczhXd3i/z8+737hCJ0S/1zc4V3d4vPzPu8yXQiJL/3MzPnV3fa7M6s"
    "ynERRGdPczMzpxM3yqu+q6pwZmZmRzMzM7czN9rP/sv9pmZmZ1MzczO3Mzf83/7r3cWHf/czMzMz51d3uqzOq76quqxzMzMzMwBE"
    "AEQARABEAEQARABEAERCREJEQkRCREJEQkRCREJEFCYUJhQmFCYUJhQmFCYUJkJmQmZCZkJmQmZCZkJmQmY="},
  {"0x09", "Luigi", '9', false,
    "edc986acc996c89e6d3faa44b58259956955526d5a5348422c2047110f670c0a720b0b710b0a73090c70090b73090a75",
    "vM3e69vtvL3eyHi9vu28y8zK3+q8y6zO7IERi6z+zMzMu77KvPuuy7yDE4uu7srM2rutytqtq+u+poarvtuonZir34RERERHVERE"
    "REntgBYQGZ51UAAAhUggAAVY6BEQEBEZcCAgAAVAIAIACGAAAAAAAXR3cHgFRFhAeAgREBEBEQZwR3BYBUBXB0gothEBEREZdIQA"
    "WAVFKFVYSPyZiZmLr3RVUFVFRFUAJSj+us7fq710QgACVUUgAARI3du9uXWOdEIiAlVFICIkSL2rqpVFWciIiImImIiIiIn8rMyE"
    "RR766suu7t7qvM7P7t7MhHGu69zNvu3e67y93O277YRVHevczb7t3rhmgAztu+2VRFn66suu7t73MyMs7t7MyXeMqr/LrKrOlSIi"
    "PvyszrmBiLq8raqrupUCU469roeWYWab3d27vdMzY2Z73dgzhmd3iszLzM5zM2ZvT/6DY4Z3Z4q8y8zKcBZhFU74MzO3Z3jru727"
    "zddGZmVLgzMzpxM4urqrqqu0Zm/92DMzM6YzOOrv/cz+z868zIMzczOnMzf87/3c7u7738gzMzMz12doq7u9qsu6qruDMzMzMwBU"
    "AFQAVABUAFQAVABUAFREVURVRFVEVURVRFVEVURVFSUVJRUlFSUVJRUlFSUVJUJVQlVCVUJVQlVCVUJVQlU="},
  {"0x05", "Pacman", '5', false,
    "beb04f45464828282c28282b28282a27282a29272b28272d28272b27272b100fa9120caa1716801b1b6921204f1c1a6a",
    "MzM5MzOTMzmTMzkzM5MzMzj/393f///93//f/d39/+M4v/////3/////3/3///zTN6EHEhgUExITFBMzM0M/8zahGHdzhymEh4d5"
    "N3dzP9M2tx2qpx27pR+qpZ2qpz/zN7hP1aR92aV/96U92ac/0ze3Hc2pHc+iH82pnc2nP9M1po7d2Z7Kx37d2J7d1z/TNr7IFBYU"
    "EQUzMzM3FBM/8zeqrFVVVRAVWVVVVXVTPfM3qqu6qqqqqqu6qqqrpz3zNqVP9WVVVXVYVVVTVbc98ze4HdAABgAzYAAAUAW3P9M3"
    "tz3VZgAAMzIAAAAFpz/zOLcd0AAGADlgAAAABac/0zi3TdAAZgA5lgAIUAWnP9M3tx3wAAAABDAAAzAFpz/zN7g/8QABAAZgABOR"
    "Gbc/09+oH83f3d3d3d3d3d+3P83f047d393d/d3d3/3d0j7dmTMXFxcUExmZMzOXFxMzmTMzZiiIiIN0MzMzOEhzMzOrph2qpB2q"
    "pR+qpZ2qpy+qR7c91al91aJv9amd1ac91De4Hc2iHc+qus+4Pc2nP9M2uH7d1H7/2qrf157f1z/zNrEHExYYEx4eGBkzM5M/0zex"
    "F3d1VYh3IoOZVnd4f/M5uru7q6q7u7u6qrq7u7vzNldmZmZ3ZmaJZnd2Z5Z4gzMzOTMzkzM5kzM5MzOTMzM="},
  {"0x06", "Pokemon", '6', false,
    "ede5afb8b6b4b6b6b675cd867c9fad767967d03e3ecd3f408a5e5e495e6ed23d3eb5393c7c32347d3135763235242830",
    "7MzszMzMzcxSIiIiIiIiIsuZtqtrq2pmUiIiIiIiIiLJVZqmZmZqplIiIiIiIiIiyVGWZ3a8zNxSIiIiIiIiIuuZtnd7t3du7M7s"
    "xCIiIiLGp6qmu6ZqrMqmamtCIiIi7MzM3rqmaqvapmqnvMzNzsZ3emd6p3Znxmd2Z3and2zJVVVVVVVVl89En5n////81SIiQiQi"
    "IlbJmQ8k/////dUlVV5VVVJWyQSfRP////3FJQAYgABSV+lESUSf///9xSUEkAlAUlfP///5RJ+U/cUlABABAFJWz////0L5IP3l"
    "JQAAAABSXM////T0QECexSUBAAAQUlzP///5RP/0/sUlAAAAAFJcxmd2Z3dnd37lJQAAAABSXMz/+ZmZmZmsxSVVVVVVUlzNmfRJ"
    "RJRJrOUiIiIiIiJe7P/5mZmZmWzLQnIiIiJVXs5ElElElEl+yrVVVVVVVZ2tRJRJRJRJbMqmaqpqpmqsq87Mzc3czK3r13/3/2fM"
    "bHZ3dnd7y8x8z/52Z3Zu/8x6Z3d3e8vsbs77qqZqr//8bESUl2qmaq3KpumZmb7/zGxElJZqpmps5neTMzXH7n13d3Znd2d3fuen"
    "kzM5x3Zue87s3rzO7L7Kpr3c3KZqrNz////P///MyqdqpmqmamzLzt3evMzNve3OztzN3M3O7NzM3M3t7N4="},
  {"0x04", "Castlevania", '4', false,
    "32b8a81ea898229c8b0a9c9335876c1c856b0a908b0b837d276f500c6f53105a280a5a170e511f0a52170d491b0e331c",
    "diETNjYzY2Y2MzNmZ2IidhAAAzMzM2M2NjNjZjZiIgGFlBY2NjNjZjYzZmd3d0lYgABmNjczYwAANnd3d3cgCPVYdmY2MBSbuEIn"
    "d3eVyZ/yJGNmMQndhETbklV3l6RP9Vl2dhTNu4iKu7tVmZnpn/IidmFbSE27271NuFmZqI+SBHZi3YiNvdu7i71JmaSPlAV2Ctvb"
    "vb1Lu7vexJmkj5UFdltI27u9S7u7ROiapI+UBXGtiN7dTU27u4juiaSPpAVw27u7vYhNu7u73omkj5QFYtiI7d7UTbu7uqyaqK+l"
    "BWTUSNu73Y27u7WIqqivlQVi7u7d3d3du7vd74mVr6QFYt3b27vdvb293e6JpI+kBJKoiIju7d3d2IiKiaSPpAWtWERE3d3dveRE"
    "SJeUj5QFqSrd/t793bvdvqWZhY+kBf3S3d3d3d3d7b0pd4KalAX66k5ERO3dvUTUV3eEWpQF+smFjYjoiNuMJXd3UkmUBf6qdSjb"
    "1ITbkldnZ1IopAX97ZnEJJzIIAl2Z3dRWYQFqup2ackgAJYzM2ZmICikCMmlZjM3VWMzEzMzZnAo+EjJWpkzZxEQERMTMzFBKviK"
    "p3djM2czMTETEzMzVS/4SJV3Z2c3MxEREQERExAK/4+ZmXdmNjMzMzMzMzORX/hImZl3d2czMzExMzMzAAw="},
  {"0x03", "World Map", '3', false,
    "96a9a05571684d4d452744363b1f2116171612151011110f2e0d0f170e0d10100e110d0c0f0f0e0c0e0a0d0d0b0c0b09",
    "Zmd2eqzruZRIl3dmVVUxMxERIzNVVVWUSJdjEAEBEBERERESMzNUREiVIhAAAAAVERERI1U2VVRIlWZSAAAANREREiNWVbmUSJl2"
    "YQAAAAERERIzNWu5lEiZdmEAAAEQEREzMzZbuZRImXZQAAACAREiMzNeXrmESJl2AAAAABUiIzM2Wm65lEibpiAAAAE1MzMzNefe"
    "uZRIm6dhABIVZjMzMzXd/7mUSJu3ZQBVVWYzMzNWb/+7lEibunYhUyZ3PeU17d//+5RIm7t3YhFmd9/dZa/P//uUSJu7p3ZjRTZv"
    "/2zf1/+7lEibvKdmZnIi//9t1q//65RIm+7HdmdhI///1tZq91mUSJu7qnZ3MiP///re/XpVhCibu6p3elIj/////fZmpZQom7un"
    "d3qiI////+7lM1SYKJu6p3d3pzP///7uUzMimCibu6p3es6j///u5TMzIkQom7qneqzMw+7u7sMzMiJIKJu3qqeszOPu7u7FV1Ii"
    "mCibuqp3rMzDzMzszMxzOZgol6p6d8zMw3d3d3d3dXmUKJt3p3zM7MNVVVVVVVd5mCiXeqzHzMzFVVVVVVVVV5gomsfHrKzMzDEQ"
    "MxAhMlWYKZqsrMzMzMwQAAEAAABVWCmXfMzMzMzMIAARABIQVZgZmnqsfKzMzFMzNDNFQ1d4Kbu76+7Mu3U="},
  {"0x02", "Time in Words", '2', false,
    "9d9bc73fab7d6e71931f664b3d3e5a25253a0f3d2c1524291b1c280f1b1713141a0c14100f10120b100e0d0d0d0c0c0c",
    "m7u7u7u7u9u7u7u7u5mZmZuZmZmZmbu7u5mbuZm73d2RERYxETM5ljYRE2ERFr3dMWYRE2MTOZYxNmExNjG93XMRNhEREzmWMxER"
    "MZlhvd1jYRMWZmYTYTM2ZmGZkb3dMRMTETEWYRNjMzExmZG93ZMRN3MzZ5Y5mTM2k7uTvd2Id3d3d3iHmZmZu7u7u93dVCVVVVUF"
    "WIiqy7u7vb3d3UAiAEACAiQkiqy7293d7u8gQiIgRAQiJIisu93d3u7+QEIAQEQEQARYrMvd3e7u7yBVRFRVREQkiKzN3e7u7u4k"
    "VVVVVVVAJIqszO7u7t7uhVUlVVVVVViqqszMzO7u/kAEJABCAlWIqqqszMzO3e4kIgIiIAJViIqqqqqqzMzOJCICIiAiVYiIiIiI"
    "iqqqrEREREREJFVVVVVVWIiIiIogAAAAAAAAAAAAAAAAAAACh1VVVVVVVVVVVVVVVVVViHM3hmM2M3VVVYWIiKqqqqw2aZN3MzZ1"
    "VVVViIqqzMzMNjlmlzNjQAJCIiSKrMzM7jc5OXaTY0AAQAAEiszM7u5zNmljNjNABAAkBIrM7u7uqIiqyruahVhVWIiqzu7u7lIA"
    "Wqu7zKqoiIqqrM7u7u4iAiqs3b3MqqqqrMzu7v7uhCSKzd3u3MzMzMzu7u7u7sgorM7u7u7uzu7u7u7u7u4="}
};
static const size_t CW_FACE_COUNT = 10;
