#pragma once

#include <Arduino.h>

// Generated by tools/gen_faces.py from docs/faces.json: do not edit.
// The clock faces that can be installed, in the order of faces.json.
struct FaceInfo {
  const char *id, *name;
  char key;        // telnet key that installs it
  bool fits32;     // drawn for a 64x32 panel too
  const char *iconPalette;  // the colours as rrggbb, or nullptr when there is no picture
  const char *iconPixels;   // 32x32, base64 of raw deflate of one colour index per pixel, row by row
};

static const FaceInfo CW_FACES[] = {
  {"0x0B", "Football", 'B', false,
    "fdfdfd9cd8af8eba9de0984b9292948b938f70685a3885533586523d5249383439000000",
    "jVILloMwCATKL+H+910gafvWddWJEWGABMHMzd3NUpq/ty1ZAqVWSSLygnkayEWQyJxs2ZGcdrynvXlBM5JE2cTEdm6hjLfKYeMG"
    "cQfVOVX/2pnnZI75aswIAF4MQL4mACJAxhatyY8Bi5/NMyQ47cWvk3DHwk7TyodXmPvocx5wn8/rIm/+e2E+fDwBByNrPsfqMwkr"
    "I+bm8jry2i7lw3HC15OBqKG8fH7/9TSGxsOb8rXOwJf6ZTydIhvbOAn7d6T2sfq4jDUtl7gfX96tyOTU16thrq5h9ia1pLU9IiSG"
    "iA7d7amVfHz6IJ3wyzPGmNqD0EVJl16z3s2rNX8A"},
  {"0x0C", "Formula 1", 'F', false,
    "d7b7b5989293ac91938c8d8e717172457d75be3d3a605f62484c504b4449c42726000000",
    "hZKBcsQgCEShchHl//+3u2h7RnMtTjIZNzxwsUu/+nXJ1bfArlzSO14iXXYZO1NnPOTLSPwvWnyOBrFZvF5VVausUolSvJTSgrqK"
    "auime/mCjnz3ioi66g7ZEfhgPvlrvkdY4Qqzqa98JEFI3Sdf642PTePir62RrnLnO7Kht9SF6+AbDsdfWs145Bt1NHfvv+UJDZxR"
    "P7bjlXzIRyvgU9aTDw74lfbT4bs/Gew/dVXd+Vy//R/+zAqTX+Xw3zz9T34NPfwpWX/w4y//x/z2/kG3Rs7Q695/sL6NRuOxf9Zg"
    "f3k/Y58vp/ujw704/Yk5Xx/+6PN8eQWpLjrrkp/3jzrn855fkod/g+8Y/+3+5ObgfwM="},
  {"0x08", "Tetris", '8', true,
    "fbfc58fcfb5a80f7c349f2e392a1627474b75367df368c70d82e5ede24266b335a000000",
    "1ZJBFsMgCERBiBi8/307JmrIq8mui7JR5guDT2v9ceScReTY7nsQmkaElJj5xpmJL36B2tu0HS05LXjwF57+PHXYDX/m4U88dcrz"
    "KjT7d8O2RC4LzjDq6WkjrX8O9ZOfY2IqSLHNv4eJVSXtme/uakkgPvKitm0PHJmDefEv7grNkpqBX/V+vLUFjrWdGVzxB9NIlbX1"
    "DrxPNTip6htPdnB546XgimuOwsb1Xv+r+AA="},
  {"0x01", "Mario", '1', false,
    "edc9859fc78f9a9f5da57a5b6a71467c4a451e16550e0a710c0a720b0b72090b73080a60",
    "hVMLkuUgCFT56/3vu92Yl6mpqVdLJBIbaURSBdk7OFW27XqqYmNx91piDW8OOOySoVwGyG8u7mogdwfRoXnxaLwQPGhHbY6On4gZ"
    "fuo40O3yiNnHOkhkTJ1j+tmmOiiu4m2o+vYJAzrnsfGIysdyHa9MQ2Ab5sBFXWh9dvcuG3AYSpwftoCXTpBDF+ILNl1cERns4rv8"
    "9IOzmGANSQnjkxhee3cRcMwCLk/actNay7tYVYxdttYfnEXLBCx20j9yXmOjpFms3EQt8bCmFF4UeK/pYjNo8GZI+Sh8m77313f8"
    "8n+PDwfzzMjbH8nzwk8kmR+CuC/3CuYa3S9lvIvBpmCr6VpLT1zSaMYlqDuTQaVZbLwb38mucVkLLslGffG8/YspcAVTJC6s1U47"
    "GJmUjhtln0ndnaETeOfX6oMg5MKajW/+A12AZI9C9JG7/5aji2Zu9nD/8Mfl5/8QtF8Yt83W+K7/kynT/up6bYzfun7P/wA="},
  {"0x09", "Luigi", '9', false,
    "edc986acc996c89e6d3faa44b58259956955535c4f1f175a0c0a720b0b72090b73080a5e",
    "fVNbgsMgCBSVp/e/785g2m1/SmpCGd5gJqgq+Em+K90cbEFYLYvGgz8ohIuIU5jZ/4Ns0LD105esL5zgtaeswo4F/Uf4SXea+n7I"
    "9MWdKh9iMsRPmeogHd1nklH1YiIDj8ixMceVb37Juo03iW0zG3aAbz2b3LVu8wEMCkOJD4UionjaRdv/htHFdR5V+HA06vSDWmxD"
    "hqQ2/SPVqdOruuBif2xv5jSp0Xlu2je5KUIBn/OFgwV+m4aKES38RefNVLcenVPhqKJ6ZnVnhbiX9W0Sz3x7Pj2rnvkND/eSX7ib"
    "+Rh58dMd+/QfttZcM67/PNCOpuxXuSL/uVg+dDBgcc/3/rAi1LlYfpRjF1TUTu9P78tqMmMyvhaSMUbI28qyC+dGdF/2gWfvonFn"
    "RHQTBmXDT3182ZbGs+EVJnQXb0K/5K7xgzNc8Q50A5gG8yRs/3i3+2kQr8tj/YrfN+e5P/FYX+qV/XG4T7+O6Px5Nnfqx/kD"},
  {"0x05", "Pacman", '5', false,
    "c6b9505d5a453434401a1b6c1b1b681e1e5b100fa912119c1b1a6b1b186f120ca9000000",
    "hVMBjsMwCGuAEhL+/9+zSdLd7SaNSBThQgx1M79ZhKmajRGhYaZ46DDmQm/gMwjAjK7e2bF2zRRvV7a3s00Dzlv7cKuI8Gr2z6bu"
    "ns3mhA/GafCSwf4TfTQ9xYw+QogjluovU5p1Y30Plza6ocKGsd6qf97gDK/eU26ruPzC73F4Y5JDr6bg/QkmYyev1yRS8xHwPn3O"
    "7t4ROEPGPnG/rfnWHt5tPnhTa9d1SV2PgAttxNd+MCd5In0VMwZggv5DC28aTOWrfuNnfuKgvsZb4S/81FePqj/46l/124gsv/kZ"
    "Nx/d/lkQRz72tv+CdMJ8MZImb8ph7otu6wukUzO29HN8f/SDhMyac+undj6PfshNuH8oZ3l+xQAeXbe+8LbcED08fgzg+BfIHJpc"
    "+pjteti3G+c1RZQ+uS+RzVke9jirPyRD8/2kiE4Yr0E/jC/53X4A"},
  {"0x06", "Pokemon", '6', false,
    "ede5afb6b6b675cd86798d8bd03e3ecd3f408a5e5e495e6ec43b3d7c32347632351d2128",
    "dVOLYsMgCNQh4eH//+8ORGvbjWpqch4coG5mbi97+ruZiugYmj/YFy5EMl72D8489E//nv6ZWRWP4dASkw4f3PCrGX2YrTC6N5R2"
    "1/peOGt9t/Cd8de0a42HmTyXCduE3ikyl5VgytH7M0xE2ux04UH0pCfewKc3vDXsaa1hyY56UNTkxklaE0rc1vfcIXT4OdJ/OaY+"
    "pbdpnvgyLK1wgoRGTTz5PdB+45IKaS785r9qg8n+5T8cyLax838qf+AS6csaI/Rd9qC3H3x0kjeKOpofMgajf3r3x4bd+DkP27D9"
    "Ps6Ir8Y8JwZ6j3feqanhiHCk43UePNqxcl84gkPPrKM1sl8rvvCOF/E9c9HkF370ONzJD0wMxWRL33d98b/x0IC4eQc070FIGHVz"
    "Kl410Or47Ptx9Kz8fXHyxa+K+LVM7Bc="},
  {"0x04", "Castlevania", '4', false,
    "32b8a81ea8981b9c8e35876c1c856b0b8a84276f500c6f530e5a220e511f0a52170d3b1a",
    "ZZMJksQgCEVFkEXuf9/5oEmmqqlU08ljE2GtSTRpzTXxrIV/kFXSmgZk0myKH7p29dAcpGJMHzz6Cpuowr2DtV8HayYii8fQFNHL"
    "B7H5VkY1hU3CLJOIm9OwDci8t00pbs6c8LfixLHBVR3Ki8K5/M9pSDYrXFugtQxCNW2Oik/te3lptooPzkPWGr4/35bgy6X4QvT/"
    "HFWqxetPOJbuLHp4vcHg4eOJrm+NxT//tzi+3D0QX29+hH3yX4XGe4TG4ZT7RxDfxDJO/F+8T37nwcbIBMmvTNWA/+HiSMfMX+n1"
    "Amy3freJ/mXW84jjAlQOz6+trzBuVZdFc0ea/DJAs2BElOXyqFjV1e6TOmO6YIDSm6djImZfazXYSM4MEqt3/tyYBsb8oaeYSrsj"
    "SmJ4lQiUu04xBXthymBMRf80rHB9RFqsU0lPXc23MjhaYL1NRINeweJE4qK8/S6n+WBM+czyt1Mu1utB4xiO4TDImvWzQ+fzvArn"
    "PP4QeVb68lppHCb+AA=="},
  {"0x03", "World Map", '3', false,
    "a6b7b498b19e7a8e886a6d6f51665739624f5c494433443923443268191a2d262d000000",
    "hdOLksMgCAVQBQwG/v9/e9HtxkdrnclrDiSAE/dp3ffwoKLKzDjXOrkykZBIFuEIkFIQUs2suQhRzimlLB4BweY2vl8akyI2sktd"
    "vt89Z+78X8DoORNT492RCkcdZeK3ozwsIvaZ3351ZwtHZ6s7Q4VxU6Px3VFAv9aJH0eyavjfsc0fg/N9jftjNmZ+2L8o/uhS1I/7"
    "f/Zf+ehw8GqbY3rPbY3oxZ8GQ/Xy+5pdx+xL7Jv3aaifHPN0O3jrb3FbfM33X27MZMak0mhzwn+QiBKu1MIX186JC390M9V+WKt1"
    "ff8L"},
  {"0x02", "Time in Words", '2', false,
    "a3a2cc9694c340ad7e737399226b4e4a4d6a3a3a5911413027283d2523371d2334000000",
    "pVILrsMwCAsFAiH3v+8MWaf+Nj3puVEVxcRA8Jz/xAaY4Scic5rU1uo0aXmTJtviRXCQp7LNFfAOB2/J1xacFV+CGW55zba6b/bh"
    "U3ZLjVWFZAKEJ3fQr7S4kiWVguTmL+0NZfcxhjv5iDvfG3MjbcTYKPcrz01JEdI7dfAat/udiZTAq1K78drcVb27d+1QuOnriBG1"
    "Rif2K49jRweOBhBzb0CRnPFDFeoPPGpmYqA1/s6voKcH6oDmwtt4vWTho4TUC22BGuXawRNFh9+REtlPlKswX6zYccgvOXOJmnrs"
    "N0+8pC0CPhO8f3ZymqLUNy1zYMqYFEo8TiHdNFd+XUbAwL+YKXJK5/oC7hk//Mfpq18GffDERSF+sS8="}
};
static const size_t CW_FACE_COUNT = 10;
