# Build step: turns docs/faces.json, the one list of clock faces, into lib/cw-commons/Faces.h for the
# firmware: which faces can be installed, their telnet keys, which fit a 64x32 panel and their pictures.
# Edit faces.json (and platformio.ini for the build), never the header.
import json, os, re
try:
    Import("env")
    root = env["PROJECT_DIR"]
except NameError:  # run by hand: python3 tools/gen_faces.py
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

src = os.path.join(root, "..", "docs", "faces.json")
dst = os.path.join(root, "lib", "cw-commons", "Faces.h")

# Telnet commands main.cpp already uses: a face can't take them as its key
RESERVED = set("RCXLUPThSNGYDW")


def c_string(text, width=100):
    if not text:
        return "nullptr"
    return "\n    ".join('"%s"' % text[i:i + width] for i in range(0, len(text), width))


faces = json.load(open(src))
ids, keys = set(), set()
for face in faces:
    if not re.fullmatch(r"0x[0-9A-F]{2}", face["id"]):
        raise SystemExit("faces.json: bad id %r" % face["id"])
    if len(face["key"]) != 1 or face["key"] in RESERVED:
        raise SystemExit("faces.json: %s: key %r is not one character that is free" % (face["id"], face["key"]))
    if not re.fullmatch(r"[A-Za-z0-9 .+-]+", face["name"]):
        raise SystemExit("faces.json: %s: the name goes into JSON and C strings as it is: letters, digits, space and .+-" % face["id"])
    if face["id"] in ids or face["key"] in keys:
        raise SystemExit("faces.json: %s: id or key used twice" % face["id"])
    ids.add(face["id"])
    keys.add(face["key"])

rows = []
for face in faces:
    icon = face.get("icon") or {}
    rows.append('  {"%s", "%s", \'%s\', %s,\n    %s,\n    %s}' % (
        face["id"], face["name"], face["key"], "true" if "64x32" in face["panel"] else "false",
        c_string(icon.get("palette")), c_string(icon.get("pixels"))))

out = ("#pragma once\n\n#include <Arduino.h>\n\n"
       "// Generated by tools/gen_faces.py from docs/faces.json: do not edit.\n"
       "// The clock faces that can be installed, in the order of faces.json.\n"
       "struct FaceInfo {\n"
       "  const char *id, *name;\n"
       "  char key;        // telnet key that installs it\n"
       "  bool fits32;     // drawn for a 64x32 panel too\n"
       "  const char *iconPalette;  // the colours as rrggbb, or nullptr when there is no picture\n"
       "  const char *iconPixels;   // 32x32, base64 of raw deflate of one colour index per pixel, row by row\n"
       "};\n\n"
       "static const FaceInfo CW_FACES[] = {\n" + ",\n".join(rows) + "\n};\n"
       "static const size_t CW_FACE_COUNT = %d;\n" % len(faces))

if not os.path.exists(dst) or open(dst).read() != out:
    open(dst, "w").write(out)
