# Build step: gzips lib/cw-commons/settings.html into SettingsWebPage.h, which the
# web server sends compressed. Edit the .html, never the header.
import gzip, os
Import("env")

src = os.path.join(env["PROJECT_DIR"], "lib", "cw-commons", "settings.html")
dst = os.path.join(env["PROJECT_DIR"], "lib", "cw-commons", "SettingsWebPage.h")

data = gzip.compress(open(src, "rb").read(), 9, mtime=0)
lines = []
for i in range(0, len(data), 20):
    lines.append("  " + ",".join("0x%02x" % b for b in data[i:i + 20]))
out = ("#pragma once\n\n#include <Arduino.h>\n\n"
       "// Generated by tools/gzip_page.py from settings.html: do not edit.\n"
       "const uint8_t SETTINGS_PAGE_GZ[] PROGMEM = {\n" + ",\n".join(lines) + "\n};\n"
       "const size_t SETTINGS_PAGE_GZ_SIZE = %d;\n" % len(data))

if not os.path.exists(dst) or open(dst).read() != out:
    open(dst, "w").write(out)
